# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# This key can be left empty. The pipeline will then be provided from a default configuration during training.
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    # model_confidence: linear_norm
    loss_type: cross_entropy
  - name: ResponseSelector
    epochs: 100
    # model_confidence: linear_norm
    loss_type: cross_entropy
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0
    model_confidence: 'linear_norm'
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["number"]
    timeout : 3
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: "SpacyEntityExtractor"
  # dimensions to extract
    dimensions: ["PERSON", "TIME"] # (more options at https://spacy.io/api/annotation#section-named-entities)
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    # Confidence threshold for the `core_fallback_action_name` to apply.
    # The action will apply if no other action was predicted with
    # a confidence >= core_fallback_threshold
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
    restrict_rules: True
    check_for_contradictions: True

