on:
  push:
    branches:
      - master
    paths:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: action_server
      name: Build an action server with a custom actions
      uses: RasaHQ/action-server-gha@master
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        docker_image_name: 'eccezarathustra/eccebot'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: ${{ github.sha }}
    
    - name: Upgrade Rasa X deployment
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm repo add rasa-x https://rasahq.github.io/rasa-x-helm ; helm upgrade rasa-x-1604487544 --install --reuse-values --set app.name=${{ steps.action_server.outputs.docker_image_name }} --set app.tag=${{ steps.action_server.outputs.docker_image_tag }} rasa rasa-x/rasa-x
        kubeconfig: '${{ secrets.KUBECONFIG }}'
        # Upgrade the helm release using output parameters from the `action_server` step
