on:
  push:
    branches:
      - master
    paths:
    - 'actions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Action Server Image
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: action_server
      name: Build an action server with a custom actions
      uses: RasaHQ/action-server-gha@master
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        docker_image_name: 'eccezarathustra/eccebot'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: ${{ github.sha }}
        requirements_file: 'actions/requirements-actions.txt'
  
  deploy:
    runs-on: ubuntu-latest
    name: Deploy built image to GKE
    needs: build
    steps:
    - name: Authenticate GCP
      if: env.ACTIONS_CHANGED == 'true'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - name: Update Helm 
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          helm repo add rasa-x https://rasahq.github.io/rasa-x-helm
          helm upgrade rasa-x-1604487544 rasa-x/rasa-x \
          --namespace test-1 \
          --reuse-values --set app.name="eccebot" --set app.tag="${{ github.sha }}"
