on:
  push:
    branches:
      - master
    paths:
    - 'actions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Action Server Image and Deploy
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - id: action_server
      name: Build an action server with a custom actions
      uses: RasaHQ/action-server-gha@main
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        docker_image_name: 'eccezarathustra/eccebot'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        rasa_sdk_version: '2.3.0'
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: ${{ github.sha }}
        requirements_file: 'actions/requirements-actions.txt'
  
    - name: Connect to gcloud action server
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: test
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: gcloud compute ssh --zone "europe-west2-c" "rasa-x-server" --project "ecce-300006"
  
    - name: Upgrade Rasa X deployment on GCLOUD VM
      run: |
        # More information: https://rasa.com/docs/rasa-x/installation-and-setup/install/helm-chart/

        # Upgrade the helm release using output parameters from the `action_server` step
        helm upgrade --install --reuse-values \
          --set app.name=${{ steps.action_server.outputs.docker_image_name }} \
          --set app.tag=${{ steps.action_server.outputs.docker_image_tag }} rasa rasa-x/rasa-x
